fixtures:
  symlinks:
    bsd: "#{source_dir}"

  repositories:
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: '1.2.5'
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '4.25.1'
    augeasproviders_sysctl:
      repo: 'https://github.com/hercules-team/augeasproviders_sysctl.git'
      ref: '2.0.2'
  forge_modules:
    augeasproviders: 'herculesteam/augeasproviders'
    augeasproviders_core: 'herculesteam/augeasproviders_core'
    augeasproviders_shellvar: 'herculesteam/augeasproviders_shellvar'
    augeasproviders_sysctl: 'herculesteam/augeasproviders_sysctl'

