Gemfile:
  optional:
    ':extra':
      - gem: 'ipaddress'
    ':testextra':
      - gem: 'rspec'
        version: '~> 3.4.0'
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
.rubocop.yml:
  extra_configs:
    RSpec/RepeatedExample:
      Enabled: False
    Style/MessageSpies:
      EnforcedStyle: receive

